# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @import Rcpp
#' @useDynLib regexcite, .registration = TRUE
#' @export
mul_func <- function(a, b) {
    .Call(`_regexcite_mul_func`, a, b)
}

